language: python
python:
  - "3.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - cd fw/rbcx-coprocessor
  - platformio run -e hw10 -e hw11
