name: PlatformIO CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install platformio
      - name: Build examples
        run: platformio run --project-dir="fw/rbcx-coprocessor/" --project-conf="fw/rbcx-coprocessor/platformio.ini" -e hw11_stlink -e hw11_bootloader -e hw11_stlink_bootloader